print(" Add code in main in Master1")
print(" Add code in main in Master2")
print(" Add code in main in Master3")
print(" print Master")
print(" Add code in main in Master1")
print(" Add code in main in Master2")
print(" Add code in main in Master3")